{% set name = "hysetter" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hysetter-{{ version }}.tar.gz
  sha256: 4a93eed1d6405fcb77e99482fb24979355bd5c4c21f7881ed5dd12cfa2b49910

build:
  entry_points:
    - hysetter = hysetter.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >=3.10
    - boto3
    - dask-expr >=1.1
    - flox
    - geopandas-base
    - numba
    - numbagg
    - planetary-computer
    - py3dep <0.18,>=0.17
    - pyarrow >=1.0.1
    - py7zr
    - pydantic >=2.7.1
    - pydaymet <0.18,>=0.17
    - pygeohydro <0.18,>=0.17
    - pygeoutils <0.18,>=0.17
    - pygridmet <0.18,>=0.17
    - pynhd <0.18,>=0.17
    - pynldas2 <0.18,>=0.17
    - pyogrio
    - pystac-client
    - pyyaml
    - rich-click >=1.8.2
    - typing-extensions
    - xarray-spatial

test:
  imports:
    - hysetter
  commands:
    - pip check
    - hysetter --help
  requires:
    - pip

about:
  summary: Subset hydroclimate data using HyRiver over CONUS.
  home: https://github.com/hyriver/hysetter
  license: MIT
  license_file: LICENSE
  doc_url: https://hysetter.readthedocs.io

extra:
  recipe-maintainers:
    - cheginit
