{% set python_min = "3.10" %}
{% set name = "hysetter" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hysetter-{{ version }}.tar.gz
  sha256: 26838f2501f8f478b872bec3dad04247c212f2a61e4c1c64ba1cb1532f880300

build:
  entry_points:
    - hysetter = hysetter.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - boto3
    - dask-expr >=1.1
    - geopandas-base >=1
    - planetary-computer
    - pyarrow >=1.0.1
    - pydantic >=2.7.1
    - pydaymet >=0.19.4,<0.20
    - pygeohydro >=0.19.4,<0.20
    - pygeoutils >=0.19,<0.20
    - pygridmet >=0.19.4,<0.20
    - pynhd >=0.19.4,<0.20
    - pynldas2 >=0.19,<0.20
    - pyogrio
    - pystac-client
    - pyyaml
    - rich-click >=1.8.2
    - seamless-3dep >=0.3
    - typing-extensions
    - xarray-spatial

test:
  imports:
    - hysetter
  commands:
    - pip check
    - hysetter --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Subset hydroclimate data using HyRiver over CONUS.
  home: https://github.com/hyriver/hysetter
  license: MIT
  license_file: LICENSE
  doc_url: https://hysetter.readthedocs.io

extra:
  recipe-maintainers:
    - cheginit
